---
title: "Replication testing"
author: "Sarah R. Alewijnse"
date: "30/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

The aim of this is to test results from our new packages and functions against the manuscript results.

## Full test

```{r load-functions}
library(here)
library(knitr)
library(tidyverse)
source(here::here("analyses",
                  "code",
                  "load_results.R"))
source(here::here("analyses",
                  "code",
                  "scale_inf_functions.R"))
```

```{r load-results}
full_test <- mergeSummaryResults(42, here::here("outputs",
                                                "full_test"))
```

```{r epidemic-size}
full_test_size <- epidemic.size(full_test)
kable(full_test_size, digits = 1)
```

```{r epidemic-duration}
full_test_duration <- epidemic.duration(full_test)
kable(full_test_duration, digits = 1)
```

## Full test with updated loop

```{r load-results-new-loop}
full_test_new_loop <- mergeSummaryResults(42, here::here("outputs",
                                                "full_test_main_loop"))
```

```{r epidemic-size-new-loop}
full_test_new_loop_size <- epidemic.size(full_test_new_loop)
kable(full_test_new_loop_size, digits = 1)
```

```{r epidemic-duration-new-loop}
full_test_new_loop_duration <- epidemic.duration(full_test_new_loop)
kable(full_test_new_loop_duration, digits = 1)
```

## Updated duplicate removal

```{r load-results-dupes-removed}
dupes_removed <- mergeSummaryResults(42, here::here("outputs",
                                                "full_new_dupes_removed"))
```

```{r epidemic-size-dupes-removed}
dupes_removed_size <- epidemic.size(dupes_removed)
kable(dupes_removed_size, digits = 1)
```

```{r epidemic-duration-dupes-removed}
dupes_removed_duration <- epidemic.duration(dupes_removed)
kable(dupes_removed_duration, digits = 1)
```

## Different seed

```{r load-results-diff-seed}
diff_seed <- mergeSummaryResults(42, here::here("outputs",
                                                "seed_125"))
```

```{r epidemic-size-diff-seed}
diff_seed_size <- epidemic.size(diff_seed)
kable(diff_seed_size, digits = 1)
```

```{r epidemic-duration-diff-seed}
diff_seed_duration <- epidemic.duration(diff_seed)
kable(diff_seed_duration, digits = 1)
```

## More recrudescense

```{r load-results-more-recrud}
more_recrud <- mergeSummaryResults(42, here::here("outputs",
                                                "more_recrudescense"))
```

```{r epidemic-size-more-recrud}
more_recrud_size <- epidemic.size(more_recrud)
kable(more_recrud_size, digits = 1)
```

```{r epidemic-duration-more-recrud}
more_recrud_duration <- epidemic.duration(more_recrud)
kable(more_recrud_duration, digits = 1)
```

## Rerun with edited command line

## More recrudescense

```{r load-results-new-cmd}
new_cmd <- mergeSummaryResults(42, here::here("outputs",
                                                "test_pulled_out_options"))
```

```{r epidemic-size-new-cmd}
new_cmd_size <- epidemic.size(new_cmd)
kable(new_cmd_size, digits = 1)
```

```{r epidemic-duration-new-cmd}
new_cmd_duration <- epidemic.duration(new_cmd)
kable(new_cmd_duration, digits = 1)
```

